apiVersion: skaffold/v2beta24
kind: Config
metadata:
  name: otus-micro
build:
  tagPolicy:
    envTemplate:
      template: "v1"
  artifacts:
    - image: strider2038/otus-micro-4-identity-service
      context: services/identity-service
      docker:
        dockerfile: build/package/identity-service/Dockerfile
        buildArgs:
          APP_VERSION: local
    - image: strider2038/otus-micro-4-identity-migrations
      context: services/identity-service
      docker:
        dockerfile: build/package/migrations/Dockerfile
    - image: strider2038/otus-micro-4-echo-service
      context: services/echo-service
      docker:
        dockerfile: build/package/echo-service/Dockerfile
        buildArgs:
          APP_VERSION: local
deploy:
  helm:
    releases:
      - name: "identity-service"
        namespace: "otus"
        chartPath: "services/identity-service/deployments/identity-service"
        wait: true
        valuesFiles:
          - "deploy/identity-values.yaml"
      - name: "echo-service"
        namespace: "otus"
        chartPath: "services/echo-service/deployments/echo-service"
        wait: true
