/*
 * Echo Service
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package api

import (
	"context"
	"net/http"
)

// EchoApiRouter defines the required methods for binding the api requests to a responses for the EchoApi
// The EchoApiRouter implementation should parse necessary information from the http request,
// pass the data to a EchoApiServicer to perform the required actions, then write the service results to the http response.
type EchoApiRouter interface {
	GetCurrentUserInfo(http.ResponseWriter, *http.Request)
}

// EchoApiServicer defines the api actions for the EchoApi service
// This interface intended to stay up to date with the openapi yaml used to generate it,
// while the service implementation can ignored with the .openapi-generator-ignore file
// and updated with the logic required for the API.
type EchoApiServicer interface {
	GetCurrentUserInfo(context.Context, User) (ImplResponse, error)
}
