/*
 * Echo Service
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package api

import (
	"context"
	"net/http"
)

// EchoApiService is a service that implents the logic for the EchoApiServicer
// This service should implement the business logic for every endpoint for the EchoApi API.
// Include any external packages or services that will be required by this service.
type EchoApiService struct {
}

// NewEchoApiService creates a default api service
func NewEchoApiService() EchoApiServicer {
	return &EchoApiService{}
}

// GetCurrentUserInfo -
func (s *EchoApiService) GetCurrentUserInfo(ctx context.Context, user User) (ImplResponse, error) {
	if user.ID == 0 {
		return Response(http.StatusForbidden, Error{
			Code:    http.StatusForbidden,
			Message: "Access denied",
		}), nil
	}

	return Response(200, user), nil
}
