/*
 * Echo Service
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package api

type User struct {
	ID    int64  `json:"id,omitempty"`
	Email string `json:"email,omitempty"`
}
